services:
    go-fmt:
        image: ghcr.io/oullin/go-fmt:latest
        working_dir: /work
        volumes:
            - ${PWD}:/work
        environment:
            HOST_PROJECT_PATH: ${PWD}
            GOCACHE: /work/storage/.cache/go-build
            GOPATH: /work/storage/.cache/gopath
            GOMODCACHE: /work/storage/.cache/gopath/pkg/mod
            TURBO_CACHE_DIR: /work/storage/.cache/turbo
        command: ['help']
