services:
    go-fmt:
        image: ghcr.io/oullin/go-fmt:latest
        working_dir: /work
        volumes:
            - ${GO_FMT_PROJECT_DIR:-${PWD}}:/work
            - go-fmt-cache:/cache
        environment:
            HOST_PROJECT_PATH: ${GO_FMT_PROJECT_DIR:-${PWD}}
            GOCACHE: /cache/go-build
            GOPATH: /cache/gopath
            GOMODCACHE: /cache/gopath/pkg/mod
        command: ['help']

volumes:
    go-fmt-cache:
        name: go-fmt-cache
